### ISSUE TITLE
Loadout menu inaccessible to all classes except Scout.

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2#54]
### When I go to test my custom weapons I find that all loadouts except Scout's are inaccessible. 
* Clicking the LOADOUT button in the menu will open Scout's loadout no matter what class you are playing. 
* Attempting to click the EDIT LOADOUT button from class selection does not function altogether.

### To Reproduce

1. Open menu.
2. Click LOADOUT in menu.
3. Try to click EDIT LOADOUT from class selection.

### Expected behavior

The loadout buttons should either open the menu to choose which classes loadout to edit or (more preferrably) open the loadout of the class you are playing.

### Media/Files

https://user-images.githubusercontent.com/91832803/203164607-8b1394c6-2bc3-48d9-bf53-11e3df98d250.mp4

### Additional context

I have not found where loadout are stored. If I found where it was located I would presumably be able to circumvent this issue by editing the file directly.

**Comment by CriticalFlaw** [comment]
Fixed in 26b835f919d3af6d1b2aab2e207f729a015a64b9 on the `dev` branch. Give it a try now.

Now when you click on the Loadout button from the main menu it will go your current class and if you hover over a class on the class selection screen then click on Edit Loadout it will too go to the "selected" class.
